export const GET_BLOG_CONTENT = 'GET_BLOG_CONTENT';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SET_CURRENT_HEADER = 'SET_CURRENT_HEADER';
export const SET_HEADER_BACKGROUND = 'SET_HEADER_BACKGROUND';

export const GET_FAQ_CONTENT = 'GET_FAQ_CONTENT';
export const GET_POST_CONTENT = 'GET_POST_CONTENT';